### ISSUE TITLE
[M3][M4][M6]-[Add a private constructor to hide the implicit public one][Add the missing @deprecated Javadoc tag.][Remove this unused private method.]

### ISSUE THREAD

**Issue by adityakonada** [munterkalmsteiner/inception#79]
**M3-Add a private constructor to hide the implicit public one**
The utility classes are better utilized when declared final and each individual private constructor is defined. This reduces the effort of a parameterless constructor which could be used elsewhere in the code. Making the class final is not only a good practice but also eliminates the usage of these utility classes in other subclasses. However, private constructors would always be able to extend themselves to other classes.

**M4-Add the missing @deprecated Javadoc tag.**
The packages in any Java code are created as a namespace. And these namespaces contain various elements such as classes, interfaces, methods, and functions. One cannot reduce or deprecate a package as it has unknown implications. But one can always remove the public classes and methods which won't be used anymore giving the modern tools (IDE's) to notify the users or developers that there is no such field or class.

**M6-Remove this unused private method**
Both inefficient usages of memory and power are considered a bad practice in software development. Similarly, the unused private methods in the code are only a burden to the size of the code. As they are never executed it is a good practice to remove them totally leading to a better understanding of the code and increase in maintainability.
